### PR TITLE
Require ruamel.yaml >=0.16.10

### PR DESCRIPTION
**Pull request by dmyersturnbull**
Fixes issue #184

### CODE REVIEW

**Comment by dmyersturnbull** [comment]
On a similar note, it may be worth using more complete version ranges:

```
python_requires=">=3.7, <=3.9"
```

And:
```
        "requests",
        "ruamel.yaml >=0.16, <1.0",
        "ruamel.yaml.jinja2 >=0.2, <1.0",
        "stdlib-list >=0.7, <1.0",
        "pip >=20",
        "setuptools >=30.3",
        "rapidfuzz >=0.7.6, <1.0",
        "progressbar2 >=3, <4",
        "colorama >=0.4, <1.0",
```

**Comment by marcelotrevisani** [comment]
You are completely right, it is better to limit a bit more the dependencies or to pin it. However, I was thinking to let it more loosely and just limit it when necessary, I know it is not the best alternative. I just would like to remove the upper bound constrains and if you like can you add those lower bounds constrains please?

**Comment by marcelotrevisani** [comment]
After it gets merged we can generate a new version for grayskull

**Comment by marcelotrevisani** [comment]
I will merge it as it is for now, we can update the requirements later then
thanks for fixing this

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
